version: "2.7"
services:
  
  devopsproject:
 
    build: /var/lib/jenkins/workspace/DevopsProject
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_2:3306/tpachato?autoReconnect=true&useSSL=false
     
  
  mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    ports:
      - 3311:3306